AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1.1
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/xmlhttprequest-ssl/autotest.watchr'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Lint/ScriptPermission:
  Exclude:
    - 'bin/*'
