default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

test:
  <<: *default
  database: playersapi_test

development:
  <<: *default
  database: playersapi

production:
  <<: *default
